apiVersion: v1
kind: Pod
metadata:
  name: my-application
spec:
  containers:
  - name: my-application
    image: my-application-image
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1024Mi
