apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: my-app
    image: my-app-image
    envFrom:
    - secretRef:
        name: my-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  MY_ENV_VAR: 