apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: my-app
    image: my-app-image
    volumeMounts:
    - name: my-app-data
      mountPath: /data
  volumes:
  - name: my-app-data
    persistentVolumeClaim:
      claimName: my-app-data-claim